project:
  type: website
  output-dir: docs
   
website:
  page-navigation: true
  title: "Daiyu Guan"
  site-url: https://ngdewanyi.github.io/guandaiyu.github.io
  favicon: images/site-logo.png
  repo-url: https://github.com/ngdewanyi/guandaiyu.github.io
  repo-actions: [edit, issue]
   
  page-footer:
    left: |
      Ocean University of China<br>
    right: |
      Made with [Quarto](https://quarto.org/)<br>
     
  navbar: 
    background: "#1a5276"
    search: true
    right: 
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "中文"
        href: Chinese.qmd

format:
  html:
    theme: styles.scss
    css: assets/style.css
    toc: true
    toc-position: right
    toc-depth: 3